# Generated by Django 3.1.3 on 2021-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_station_id', models.IntegerField()),
                ('dest_station_id', models.IntegerField()),
                ('oct_adt_fare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
                ('station_id', models.IntegerField()),
            ],
        ),
    ]
