# Generated by Django 3.1.3 on 2021-04-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='product_category_name_english',
        ),
    ]
