# Generated by Django 3.1.3 on 2021-04-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Offer_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
            preserve_default=False,
        ),
    ]
