# Generated by Django 3.1.3 on 2021-04-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offer_offer_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
