# Generated by Django 3.1.3 on 2021-04-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_offer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer2',
        ),
    ]
