# Generated by Django 3.1.3 on 2021-04-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='Offer_date',
        ),
    ]
