# Generated by Django 3.1.3 on 2021-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='product_category_name',
            new_name='Product_category_name',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='Product_image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
