# Generated by Django 3.1.3 on 2021-04-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_offer_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='Offer',
        ),
    ]
