# Generated by Django 3.1.3 on 2021-04-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_offer_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='Offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productinfo'),
            preserve_default=False,
        ),
    ]
