# Generated by Django 3.1.3 on 2021-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_offer_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Offer',
            new_name='Offer_key',
        ),
    ]
