# Generated by Django 3.1.3 on 2021-04-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
