# Generated by Django 3.1.3 on 2021-04-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssociation_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('Dest_Product_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dest_Product_Cat', to='products.productcategory')),
                ('Src_Product_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Src_Product_Cat', to='products.productcategory')),
            ],
        ),
    ]
