# Generated by Django 3.1.3 on 2021-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210412_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
