# Generated by Django 3.1.3 on 2021-04-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_exchangerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRequest',
        ),
    ]
