# Generated by Django 3.1.3 on 2021-04-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_exchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Like_date',
        ),
    ]
